[AA] Adding missing categories in Apparel & Accessories
Shopify/product-taxonomy pull request #332
Opened 2024-09-26 12:41 UTC by ornanatan

Adding some categories that was missing in A&A:
Apparel & Accessories > Clothing Accessories > Fashion Face Masks
Apparel & Accessories > Clothing Accessories > Hair Accessories > Hair Bands
Apparel & Accessories > Clothing > Activewear > Leotards & Unitards

2024-10-05 22:15 UTC, ricardotejedorsanz requested changes
Changes make sense with a minor formatting issue to fix.
We'll also need to run mappings.

2024-10-05 22:15 UTC, ricardotejedorsanz commented on data/categories/aa_apparel_accessories.yml
> +  - age group
This should be `age_group`.

2024-10-07 05:28 UTC, ornanatan commented on data/categories/aa_apparel_accessories.yml
> +  - age group
fixed

2024-10-08 10:06 UTC, ricardotejedorsanz approved these changes

2024-10-08 10:06 UTC, merged