expend bulb cup type attribute
Shopify/product-taxonomy pull request #343
Opened 2024-09-30 07:01 UTC by ornanatan

expend bulb cup type attribute with more values:
E5
E6
E9
E14
E17
E18
E20
E23
E29
E30
E31
E32
E39
E40
B22

2024-09-30 13:48 UTC, tylerrowsell approved these changes

2024-10-05 22:28 UTC, ricardotejedorsanz requested changes
Changes makes sense, with one fix before merging.

2024-10-05 22:28 UTC, ricardotejedorsanz commented on data/localizations/values/en.yml
> +      context: Bulb cap type
The name of `bulb_cap_type__e29` should match E29 instead of E23.

2024-10-05 22:28 UTC, ricardotejedorsanz commented on data/values.yml
> +  handle: bulb-cap-type__e29
Same here.

2024-10-08 10:24 UTC, merged