[VP] Add Commercial Vehicles category
Shopify/product-taxonomy pull request #459
Opened 2024-11-25 08:23 UTC by ornanatan

Add Commercial Vehicles category (Buses, Taxis, etc)

2024-11-27 15:30 UTC, tylerrowsell approved these changes

2024-11-29 16:54 UTC, ricardotejedorsanz requested changes
I suggest to simplify the structure to avoid overlaps with existing categories.

2024-11-29 16:54 UTC, ricardotejedorsanz commented on data/attributes.yml
> +  - bus_design_type__other
I would drop this attribute, as this brings multiple overlaps with the categories suggested: minicoach, double decker, articulated...

2024-11-29 16:54 UTC, ricardotejedorsanz commented on data/categories/vp_vehicles_parts.yml
> +  - vp-2-4-4
For consistency, I would place these categories one level below, under `Vehicles & Parts > Vehicles > Motor Vehicles`

2024-11-29 16:54 UTC, ricardotejedorsanz commented on data/categories/vp_vehicles_parts.yml
> +  - item_condition
We already have categories for `Trucks`, I wouldn't create a new area for them?

2024-11-29 16:54 UTC, ricardotejedorsanz commented on data/categories/vp_vehicles_parts.yml
> +  - upholstery_pattern
Same for Vans: we already have categories for `Vans` (electric, non-electric and hybrid).
I advise against creating a separate area to keep categories mutually exclusive.

2024-11-30 22:29 UTC, merged