Add Furniture
Shopify/product-taxonomy pull request #51
Opened 2024-01-31 16:53 UTC by tylerrowsell

Adds the Furniture vertical, and bumps version accordingly

2024-01-31 17:16 UTC, martinlaws requested changes

2024-01-31 17:16 UTC, martinlaws commented on README.md
> +| Sporting Goods | ✅ |
this says sporting goods twice?

2024-01-31 17:20 UTC, martinlaws approved these changes

2024-01-31 18:36 UTC, elsom25 approved these changes
Let's rebase commits before merge?

Also should we bump version to `v0.0.2`? v0 space is kinda wild-west, but it's also fun for it to bump with another new data set 😁

2024-02-02 21:37 UTC, merged

2024-02-04 18:44 UTC, Influ1877 commented on README.md
> +| Sporting Goods | ✅ |
K